# Generated by Django 5.2.14 on 2026-05-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('restaurant', 'Restaurant'), ('cafe', 'Cafe'), ('spot', 'Tourist Spot'), ('activity', 'Activity')], max_length=50)),
                ('themes', models.CharField(blank=True, help_text='쉼표로 구분된 테마 목록 (예: nature, healing, food)', max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.CharField(blank=True, default='', max_length=1000)),
            ],
        ),
    ]
