# Generated by Django 5.2.15 on 2026-06-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelcourse',
            name='preferences',
            field=models.TextField(blank=True, default='', help_text='자연어 여행 선호도 (AI 추천에 활용)'),
        ),
    ]
