# Generated by Django 5.2.15 on 2026-06-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_url',
            field=models.URLField(blank=True, default='', help_text='카카오맵 장소 URL', max_length=1000),
        ),
        migrations.AddField(
            model_name='place',
            name='region',
            field=models.CharField(blank=True, db_index=True, default='', help_text='지역명 (예: 홍대, 강남)', max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
