# Generated by Django 5.2.15 on 2026-06-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_place_url_place_region_alter_place_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('cafe', 'Cafe'), ('spot', 'Tourist Spot'), ('activity', 'Activity'), ('accommodation', 'Accommodation')], max_length=50),
        ),
    ]
