# Generated by Django 5.2.15 on 2026-06-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryevent',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='temporaryevent',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
