# Generated by Django 5.2.15 on 2026-06-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_travelcourse_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelcourse',
            name='ai_comment',
            field=models.TextField(blank=True, default='', help_text='AI가 분석한 코스 한줄평'),
        ),
        migrations.AddField(
            model_name='travelcourse',
            name='status',
            field=models.CharField(choices=[('draft', '임시저장'), ('saved', '저장됨')], default='draft', help_text='코스 저장 상태', max_length=20),
        ),
    ]
