# Generated by Django 5.2.15 on 2026-06-23 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_travelcourse_ai_comment_travelcourse_status'),
        ('places', '0002_place_place_url_place_region_alter_place_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePlaceExclude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_places', to='courses.travelcourse')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('course', 'place')},
            },
        ),
        migrations.CreateModel(
            name='CoursePlaceKeep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kept_places', to='courses.travelcourse')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('course', 'place')},
            },
        ),
    ]
