# Generated by Django 5.2.15 on 2026-06-24 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_courseplaceexclude_courseplacekeep'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelcourse',
            name='user',
            field=models.ForeignKey(blank=True, help_text='생성자/소유자', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
