# Generated by Django 5.2.15 on 2026-06-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_travelcourse_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelcourse',
            name='departure_time',
            field=models.TimeField(blank=True, help_text='여행 출발 시간 (예: 14:00)', null=True),
        ),
        migrations.AddField(
            model_name='travelcourse',
            name='transportation',
            field=models.CharField(choices=[('car', '자차'), ('public', '대중교통')], default='public', help_text='이동 수단', max_length=20),
        ),
    ]
