# Generated by Django 5.2.15 on 2026-06-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_travelcourse_departure_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='slot_name',
            field=models.CharField(blank=True, help_text='AI가 지정한 슬롯 이름 (예: 만화카페)', max_length=50),
        ),
    ]
