# Generated by Django 5.2.15 on 2026-06-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_coursedetail_slot_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='alternative_option',
            field=models.TextField(blank=True, default='', help_text='대체 가능 옵션'),
        ),
        migrations.AddField(
            model_name='coursedetail',
            name='reason',
            field=models.TextField(blank=True, default='', help_text='AI 추천 이유'),
        ),
    ]
